name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build Docker image
      run: |
        docker build -t ishubishu/my-nest-app:latest .
        docker images
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ishubishu/my-nest-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for authentication
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Start the SSH agent
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        
        # Debugging: List SSH keys added to the agent
        ssh-add -l
    - name: Deploy to server
      run: |
        echo "Deploying to server"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ec2-user/
          git clone https://github.com/ishubishu/my-nest-app.git my-nest-app
          cd my-nest-app
          docker pull ishubishu/my-nest-app:latest
          docker-compose down
          docker-compose up --build
        EOF