name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for authentication
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 777 ~/.ssh/id_rsa
        
        # Start the SSH agent
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        
        # Debugging: List SSH keys added to the agent
        ssh-add -l
    - name: Deploy to server
      run: |
        echo "Deploying to server"
        cd ~/.ssh
        ls -al
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}