name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key for authentication
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Start the SSH agent
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        
        # Debugging: List SSH keys added to the agent
        ssh-add -l
    - name: Deploy to server
      run: |
        echo "Deploying to server"
        cd ~
        ls -al
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/ec2-user/
          git clone https://github.com/ishubishu/my-nest-app.git my-nest-app
          cd my-nest-app
          docker pull ishubishu/my-nest-app:latest
          docker-compose down
          docker-compose up --build
        EOF