deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up SSH key for authentication
    run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      eval $(ssh-agent -s)
      ssh-add ~/.ssh/id_rsa
      ssh-add -l  # Debugging: Verify key is added

  - name: Deploy to server
    run: |
      echo "Deploying to server"
      ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "bash -s" <<EOF
        set -e  # Exit on error
        cd /home/ec2-user/

        # Ensure the repo is fresh
        if [ -d "my-nest-app" ]; then
          echo "Removing existing my-nest-app directory..."
          rm -rf my-nest-app
        fi

        echo "Cloning repository..."
        git clone https://github.com/ishubishu/my-nest-app.git my-nest-app
        cd my-nest-app

        echo "Pulling latest Docker image..."
        docker pull ishubishu/my-nest-app:latest

        echo "Restarting Docker containers..."
        docker-compose down || true  # Ignore errors if no running containers
        docker-compose up --build -d  # Run in detached mode
      EOF
